URL_SERVICE = "https://6f552ff9-a423-471b-9ce5-b25bac62815f.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"
CREATE_KITS_PATH = "/api/v1/kits"
